org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
android.nonTransitiveRClass=false
android.defaults.buildfeatures.buildconfig=true
android.nonFinalResIds=false
android.enableR8.fullMode=false
ksp.useKSP2=true

kotlin.native.ignoreDisabledTargets=true
# K/N framework link 需要大堆（CI macos-14 7GB 内存）
kotlin.native.daemon.jvmargs=-Xmx6g
